namespace KHQ.Domain.DTOs
{
    public class CategoryDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageLink { get; set; }

    }

    // Generated by Cursor: wrapper to return categories with section title/description
    public class CategoryDtoNew
    {
        public List<CategoryDto> CategoriesDtos { get; set; }
        public string Title { get; set; }
        public string Main_Description { get; set; }
    }
}
