using AutoMapper;
using KHQ.Domain;
using KHQ.Domain.DTOs;
using KHQ.Domain.Entities;
using KHQ.Repo.UOW;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KHQ.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class CategoryController : ControllerBase
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IMapper _mapper;

		public CategoryController(IUnitOfWork unitOfWork, IMapper mapper)
		{
			_unitOfWork = unitOfWork;
			_mapper = mapper;
		}

		[HttpGet]
		[Route("GetAll")]
		public async Task<CategoryDtoNew> GetAll()
		{
			// Generated by Cursor: wrap categories with section meta and image links
			var categoryData = await _unitOfWork.Repository<Category>().Queryable().ToListAsync();
			var baseHome = await _unitOfWork.Repository<BaseHome>().Queryable().Where(x => x.SectionType == (int)SectionType.Category).FirstOrDefaultAsync();
			var baseHomeDto = _mapper.Map<BaseHomeDto>(baseHome);

			var result = _mapper.Map<IEnumerable<CategoryDto>>(categoryData);

            foreach (CategoryDto cat in result)
            {
                // Initialize PathLink if it's null
                if (cat.ImageLink == null)
                {
                    cat.ImageLink = "";
                }

                var images = await _unitOfWork.Repository<Image>().Queryable().Where(x => x.ImageType == ImageType.Categories).ToListAsync();

                foreach (var image in images)
                {
                    cat.ImageLink = image.PathLink;
                }
            }

            var dto = new CategoryDtoNew
			{
				CategoriesDtos = result.ToList(),
				Title = baseHomeDto?.Title,
				Main_Description = baseHomeDto?.Description
			};
			return dto;
		}

		[HttpGet]
		[Route("GetById/{id}")]
		public async Task<CategoryDto> GetById(Guid id)
		{
			var categoryData = await _unitOfWork.Repository<Category>().GetByIdAsync(id);
			var result = _mapper.Map<CategoryDto>(categoryData);
			return result;
		}
	}
}
