using KHQ.Domain;
using KHQ.Domain.DTOs;
using KHQ.Domain.ViewModel;
using KHQ.Portal.Service;
using KHQ.Srv.Caching;
using KHQ.Srv.Services;
using Microsoft.AspNetCore.Mvc;

namespace KHQ.Portal.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductSrv _ProductSrv;
        private readonly ICategorySrv _CategorySrv;
        private readonly IBrandSrv _BrandSrv;
        private readonly IImageService _imageService;
        private readonly ICacheService _cacheService;


        public ProductController(IProductSrv productSrv, ICategorySrv categorySrv, IImageService imageService, IBrandSrv brandSrv, ICacheService cacheService)
        {
            _ProductSrv = productSrv;
            _CategorySrv = categorySrv;
            _imageService = imageService;
            _BrandSrv = brandSrv;
            _cacheService = cacheService;
        }
        public async Task<IActionResult> Index(string search = "", string sortBy = "AToZ")
        {
            var products = await _ProductSrv.GetAllAsync();

            foreach (ProductVM pro in products)
            {
                // Initialize PathLink if it's null
                if (pro.PathLink == null)
                {
                    pro.PathLink = new List<string>();
                }

                var images = await _imageService.GetImagesAsync(pro.Id, ImageType.Product);

                foreach (var image in images.OrderBy(x => x.Sort))
                {
                    pro.PathLink.Add(image.PathLink);
                }
            }

            // 🔍 Search filter
            if (!string.IsNullOrEmpty(search))
            {
                products = products.Where(p =>
                    p.NameEn.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                    p.NameAr.Contains(search, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            // ↕️ Sorting
            // ↕️ Sorting
            products = sortBy switch
            {
                "PriceLow" => products.OrderBy(p => p.Capacity).ToList(),
                "PriceHigh" => products.OrderByDescending(p => p.Capacity).ToList(),
                "AToZ" => products.OrderBy(p => p.NameEn).ToList(),       
                "ZToA" => products.OrderByDescending(p => p.NameEn).ToList(),
                _ => products
            };

            // Preserve search/sort values in ViewBag
            ViewBag.Search = search;
            ViewBag.SortBy = sortBy;

            return View(products);
        }

        public async Task<IActionResult> GetById(Guid id)
        {
            var productData = await _ProductSrv.GetByIdAsync(id);
            return View(productData);
        }

        [HttpGet]
        [Route("GetAllCategories")]
        public async Task<IEnumerable<CategoryVM>> GetAllCategories()
        {
            var categories = await _CategorySrv.GetAllAsync();
            return categories;
        }
        
        [HttpGet]
        [Route("GetAllBrands")]
        public async Task<IEnumerable<BrandsVM>> GetAllBrands()
        {
            var brands = await _BrandSrv.GetAllAsync();
            return brands;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add([FromBody] ProductVM productVM)
        {
            var result = await _ProductSrv.AddAsync(productVM);
            if (result > 0)
            {
                _cacheService.ClearAll();
                return RedirectToAction("Index", "Product");
            }
            else
            {
                return BadRequest();
            }
        }


        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var productData = await _ProductSrv.GetByIdAsync(id);

            if (productData != null)
            {
                // NOTE: Code generated by Cursor
                var images = await _imageService.GetImagesAsync(productData.Id, ImageType.Product);
                var orderedImages = images.OrderBy(x => x.Sort).ToList();

                productData.PathLink = orderedImages.Select(x => x.PathLink).ToList();

                // Sort SubProducts by SortOrder to match the image order
                var sortedSubProducts = productData.SubProducts.OrderBy(x => x.SortOrder).ToList();
                
                // Ensure we do not duplicate the last image if there are fewer images than subproducts
                var usableCount = Math.Min(sortedSubProducts.Count, orderedImages.Count);

                for (int i = 0; i < sortedSubProducts.Count; i++)
                {
                    var sub = sortedSubProducts[i];
                    sub.ImageUrl = i < usableCount ? orderedImages[i].PathLink : null;
                }
                
                // Update the original SubProducts collection with the sorted order
                productData.SubProducts = sortedSubProducts;
            }

            return View(productData);
        }
        [HttpPost]
        public async Task<IActionResult> Update([FromBody] ProductVM productVM)
        {
            var result = await _ProductSrv.UpdateAsync(productVM);
            if (result > 0)
            {
                _cacheService.ClearAll();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return BadRequest();
            }
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _ProductSrv.DeleteAsync(id);
            if (result > 0)
            {
                _cacheService.ClearAll();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return BadRequest();
            }
        }

        public async Task<IActionResult> CoverSection()
        {
            var images = await _imageService.GetImagesByImageTypeAsync(ImageType.Product_Cover);
            return View(images);
        }
    }
}
